export const billPreview = [
  {
    label: "Bill Details",
    fields: [
      {
        labelName: "Recipient Bank Account Name",
        isEdited: true,
        oldValue: "fdsfdsf",
        newValue: "fdsfdsfsdf",
        type: "string",
      },
      {
        labelName: "Recipient Country",
        isEdited: false,
        oldValue: "Philippines",
        newValue: "Philippines",
        type: "string",
      },
      {
        labelName: "Recipient Currency",
        isEdited: false,
        oldValue: "PHP",
        newValue: "PHP",
        type: "string",
      },
      {
        labelName: "Recipient Bank",
        isEdited: true,
        oldValue: "ASIA UNITED BANK CORPORATION",
        newValue: "ABN AMRO BANK NV MANILA",
        type: "string",
      },
      {
        labelName: "SWIFT/BIC Code",
        isEdited: true,
        oldValue: "AUBKPHMM",
        newValue: "ABNAPH2A",
        type: "string",
      },
      {
        labelName: "Recipient Bank Account Number",
        isEdited: true,
        oldValue: "fsdf",
        newValue: "fdsfsdf",
        type: "string",
      },
      {
        labelName: "Recipient Address",
        isEdited: true,
        oldValue: "",
        newValue: "adsadsad",
        type: "string",
      },
      {
        labelName: "Recipient City",
        isEdited: true,
        oldValue: "",
        newValue: "fsfdsf",
        type: "string",
      },
      {
        labelName: "Recipient ZIP Code",
        isEdited: true,
        oldValue: "",
        newValue: "1234",
        type: "string",
      },
      {
        labelName: "Recipient Bank Account Type",
        isEdited: false,
        oldValue: "Company",
        newValue: "Company",
        type: "string",
      },
      {
        labelName: "Payment Purpose",
        isEdited: false,
        oldValue: "Business Expense",
        newValue: "Business Expense",
        type: "string",
      },
      {
        labelName: "Recipient Email",
        isEdited: true,
        oldValue: "",
        newValue: "fsf@dsadas.com",
        type: "string",
      },
      {
        labelName: "Invoice number",
        isEdited: false,
        oldValue: "",
        newValue: "INV-12345678",
        type: "string",
      },
      {
        labelName: "Issuance date",
        isEdited: false,
        oldValue: "",
        newValue: "1 June 2023",
        type: "string",
      },
      {
        labelName: "Due date",
        isEdited: false,
        oldValue: "",
        newValue: "15 June 2023",
        type: "string",
      },
      {
        labelName: "Category",
        isEdited: false,
        oldValue: "",
        newValue: "Refund",
        type: "string",
      },
      {
        labelName: "Tax",
        isEdited: false,
        oldValue: "",
        newValue: "Value Added Tax (12%)",
        type: "string",
      },
      {
        labelName: "Invoice amount",
        isEdited: false,
        oldValue: "",
        newValue: "USD 2,000",
        type: "string",
      },
      {
        labelName: "Tags",
        isEdited: false,
        oldValue: "",
        newValue: "Department - Marketing",
        type: "string",
      },
      {
        labelName: "Notes",
        isEdited: false,
        oldValue: "",
        newValue: "Refund for last month payment",
        type: "string",
      },
    ],
  },
  {
    label: "Payment Details",
    fields: [
      {
        labelName: "Recipient gets",
        isEdited: false,
        oldValue: "",
        newValue: "USD 1,912",
        type: "string",
      },
      {
        labelName: "You send",
        isEdited: false,
        oldValue: "",
        newValue: "PHP 110,940.79",
        type: "string",
      },
      {
        labelName: "Pay on",
        isEdited: false,
        oldValue: "",
        newValue: "12 June 2023",
        type: "string",
      },
      {
        labelName: "Pay from",
        isEdited: false,
        oldValue: "",
        newValue: "Main account balance",
        type: "string",
      },
      {
        labelName: "Send payment updates to",
        isEdited: false,
        oldValue: "",
        newValue: "name@email.com",
        type: "string",
      },
      {
        labelName: "Remarks for recipient",
        isEdited: false,
        oldValue: "",
        newValue: "some remarks here",
        type: "string",
      },
    ],
  },
];
